'use client'

// Re-export only what we need from framer-motion to avoid the "export *" issue
// This wrapper helps with Next.js 15 compatibility
export {
  motion,
  AnimatePresence,
  useAnimation,
  useAnimationControls,
  useInView,
  useScroll,
  useTransform,
  useMotionValue,
  useMotionValueEvent,
  useSpring,
  useVelocity,
  useTime,
  useCycle,
  useReducedMotion,
  useAnimationFrame,
  useDragControls,
  usePresence,
  useIsPresent,
  useWillChange,
  animate,
  animateValue,
  scroll,
  scrollInfo,
  spring,
  inertia,
  stagger,
  delay,
  easeIn,
  easeOut,
  easeInOut,
  anticipate,
  circIn,
  circOut,
  circInOut,
  backIn,
  backOut,
  backInOut,
  cubicBezier,
  transform,
  clamp,
  distance,
  interpolate,
  mix,
  pipe,
  progress,
  wrap,
  MotionConfig,
  LazyMotion,
  domAnimation,
  domMax,
  LayoutGroup,
  AnimateSharedLayout,
  Reorder
} from 'framer-motion'